### PR TITLE
New demo: Image Cursor with Zoom. Uses frameCallback.

### PR DESCRIPTION
**Pull request by jhannah**

### CODE REVIEW

**Comment by aphex** [comment]
I think its best if we have examples stick to features the library adds. The frameCallback is good to have there but I think its best if we show people how to use various configs inside the manager. I have modified your demo to use cursors, greedySelector and individual zoom.

**Comment by jhannah** [comment]
I like your `addEventListener("mousemove", ...)` example! Very cool! I _do_ think some sort of `frameCallback` example is important though. Did you have a use case in mind for which you think `frameCallback` would be appropriate? Let's add an example. :)

**Comment by aphex** [comment]
hmmm.. I am thinking maybe something with hand data as the library doesn't process that at all. Really anything that has to do with gestures or pointables can be handed through events and cursors. 

So maybe something using this api
http://js.leapmotion.com/api_guide#Leap_Hand

**Comment by jhannah** [comment]
OK, so I'll create a demo which just shows `direction`, `palmNormal`, `palmPosition` (etc?) in divs?

**Comment by aphex** [comment]
sounds awesome :)

**Pull request closed without merging**
